### ISSUE TITLE
gradle-assemble does not include less-files

### ISSUE THREAD

**Issue by BirgerK** [kensiprell/bootstrap-framework#10]
Hi there,

I found a case in which this plugin won't put LESS-files to the configured place.

My way to it:
- configure your project like said in documentation
- enable using LESS-files by setting option _useLess_ to _true_
- run ```./gradlew assemble ```
- check if LESS-files are stored in the configure directory

In my case they didn't. If I do a ```grails run-app``` instead of the gradle-assemble, it's all fine.

But I need to assemble the war-File on CI-Server.

Do you know about this issue?

Regards

**Comment by kensiprell** [comment]
I will have to take a deeper look at this over the weekend, but as a workaround you could try adding the line below to the end of your build.gradle:

    assemble.dependsOn processResources

However, I would like to find a cleaner solution.

**Comment by BirgerK** [comment]
That gradle-dependency doesn't work. I'm no gradle-expert and don't know why....

But my working workaround is:
```
assetCompile.dependsOn createBootstrapLess
```
I didn't try it with your task _processResources_. My project doesn't use fontAwesome-LESS-files, so this workaround is good enough for me.

**Comment by kensiprell** [comment]
That makes sense, but I am not sure that would work in all use cases. It was late for me last night when I answered your post. I will try and come up with a definite fix that does not require any extra user work tomorrow. Thanks for the feedback.

**Comment by BirgerK** [comment]
Hi again,

did you find anything?

**Comment by kensiprell** [comment]
Sorry about the delay, but since you got it working it dropped off my priority list. I'll try and find time over the weekend.

**Comment by kensiprell** [comment]
Since I no longer have time to maintain the plugin, I have disabled the issues feature and posted a warning at the top of the README.md file.
