### ISSUE TITLE
Seems not to work with older bootstrap versions

### ISSUE THREAD

**Issue by nilskuhn** [kensiprell/bootstrap-framework#11]
Hi,

unfortunately this plugin doesn't work for older versions of bootstrap :(
I am using version 2.3.2 and with the following in build.gradle:

    ext {
      bootstrapFrameworkVersion = "1.0.3"
      grailsVersion = project.grailsVersion
      bootstrapFramework = [
        version             : "2.3.2",
        //cssPath             : "",
        jsPath              : "grails-app/assets/javascripts/lib",
        useIndividualJs: true,
        useLess        : true,
        //invalidVersionFails : false
        fontAwesome    : [
          install: true,
          //version             : "4.3.0"
          useLess: true,
          //invalidVersionFails : false
        ]
      ]
      assetPipelineGradleVersion = "2.3.8"
      assetPipelineGrailsVersion = "3.0.2"
      assetPipelineLessVersion = "2.3.0"
    }

I get the following after a `gradle assemble` or `gradle war`:

    grails-app/assets/javascripts/lib
    ├── bootstrap
    │   ├── bootstrap-affix.js
    │   ├── bootstrap-alert.js
    │   ├── bootstrap-button.js
    │   ├── bootstrap-carousel.js
    │   ├── bootstrap-collapse.js
    │   ├── bootstrap-dropdown.js
    │   ├── bootstrap-modal.js
    │   ├── bootstrap-popover.js
    │   ├── bootstrap-scrollspy.js
    │   ├── bootstrap-tab.js
    │   ├── bootstrap-tooltip.js
    │   ├── bootstrap-transition.js
    │   └── bootstrap-typeahead.js
    └── bootstrap-all.js

With the following in bootstrap-all.js:

    //
    // Do not edit this file. It will be overwritten by the bootstrap-framework plugin.
    //
    //= require bootstrap/bootstrap.js
    //

But with bootstrap 2.3.2 there is no `bootstrap/bootstrap.js`.

**Comment by kensiprell** [comment]
You can include those files in another JavaScript manifest. For example, if you're using application.js to load assets, this sould work:

    //= require_tree lib/bootstrap

Does this make sense, or did I misunderstand you? Of couse, there is no need to require bootstrap-all any where.

**Comment by nilskuhn** [comment]
You are right. I can include the single bootstrap scripts by including them in another manifest. But it would be better if the generated `bootstrap-all.js` would include these files automatically.
Otherwise `bootstrap-all.js` points to not existing script `bootstrap/bootstrap.js` and I get the following from task _assetCompile_:

    Processing File 54 of 166 - lib/bootstrap-all.js
    Unable to Locate Asset: /bootstrap/bootstrap.js

By the way, in order to get all the bootstrap and font awesome assets included in _assetCompile_ task of grails asset pipeline in the first run of a `gradlew assemble` or `gradlew war` I have to let _assetCompile_ depend on all your tasks in `build.gradle`:

    assetCompile.dependsOn {[
        createBootstrapLess,
        createBootstrapJs,
        createBootstrapMixins,
        createFontAwesomeCssAll,
        createFontAwesomeCssIndividual,
        createFontAwesomeFonts,
        createFontAwesomeLessLess,
        createFontAwesomeLess,
        printBootstrapAssets
    ]}

**Comment by kensiprell** [comment]
Since I no longer have time to maintain the plugin, I have disabled the issues feature and posted a warning at the top of the README.md file.

However, you could take it over if you are interested in improving it.
