### ISSUE TITLE
I'm trying to use the plugin but the dropdown menu doesn't work

### ISSUE THREAD

**Issue by pfoletto** [kensiprell/bootstrap-framework#2]
first of all thanks for your effort
I'm trying to use the plugin but the dropdown menu doesn't work

I add the dependency to the plugin
Which are the steps to use the plugin?

**Comment by kensiprell** [comment]
Here's an [example for a drop-down menu](https://github.com/kensiprell/bootstrap-framework-sample/blob/master/grails-app/views/start/bootstrapCssExample.gsp#L41-L53) taken directly from a [Bootstrap sample](http://getbootstrap.com/examples/theme/). 

If you're new to Bootstrap, you might want to start [here](http://getbootstrap.com/getting-started/#examples), but there are hundreds for tutorials available.

**Comment by pfoletto** [comment]
I use your code in another project
so I'm sure that your code is correct

probably I need some configurations

**Comment by kensiprell** [comment]
The plugin only makes the JavaScript and CSS libraries available to your application, nothing else. If you're using the ```asset-pipeline``` plugin, read [this](https://github.com/kensiprell/bootstrap-framework/blob/master/README.md#asset-pipeline-usage). You'll have to write your own JavaScript code to make use of the Bootstrap functionality.

**Comment by pfoletto** [comment]
excuse me

I download your project and it works

I create a new project
I add a dependency of your plugin but I think does not work

I'm using windows 10, grails 3.04 & java 8.51

I copied manually the contents of directory assets and it works
what is strange for me is that plugin does NOT copy automatically the files

2015-08-08 13:46 GMT+02:00 Ken Siprell <notifications@github.com>:

> The plugin only makes the JavaScript and CSS libraries available to your
> application, nothing else. If you're using the asset-pipeline plugin,
> read this
> <https://github.com/kensiprell/bootstrap-framework/blob/master/README.md#asset-pipeline-usage>.
> You'll have to write your own JavaScript code to make use of the Bootstrap
> functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kensiprell/bootstrap-framework/issues/2#issuecomment-128970595>
> .
>



-- 
Studio Ingegneria dell'Informazione
via Marconi,1 35040 Carceri (PD)
cell 335 615 23 53
http://it.linkedin.com/in/paolofoletto
Posta Elettronica Certificata paolo.foletto[at]ingpec.eu

**Comment by kensiprell** [comment]
After you add the plugin to your build.gradle, try ```grails compile```. If it still doesn't work, post your build.gradle, the stacktrace or console output, and let me know the exact contents of your app's ```grails-app/assets/javascripts``` and ```grails-app/assets/stylesheets``` directories.

**Comment by kensiprell** [comment]
I'm closing this issue. If you still have questions or problems, please reopen it.
