### ISSUE TITLE
bootstrap and fontawesome resources not generating after clean 

### ISSUE THREAD

**Issue by sapradhan** [kensiprell/bootstrap-framework#4]
i am having some issues regenerating resources once i run clean. 
i have put `clean` section in `build.gradle` as in your sample project 

    clean {
	def javascriptsTree = fileTree("grails-app/assets/javascripts") {
		include "**/*"
		exclude "jquery*.js"
	}
	def stylesheetsTree = fileTree("grails-app/assets/stylesheets") {
		include "**/*"
		exclude ".gitignore"
	}
	delete javascriptsTree
	delete stylesheetsTree
	delete "grails-app/assets/javascripts/bootstrap", "grails-app/assets/stylesheets/bootstrap", "grails-app/assets/stylesheets/font-awesome"
     }

once this is run it deletes all the generated files and for some reason only empty bootstrap/fontawesome folders are being recreated under both javascripts and stylesheets folder. I can see zip files are being downloaded. I tried running `run-app`, `gradle assetCompile`. I am new to grails and gradle do is need to do any thing to force this?  

If i can read this `clean` segment correctly, it will also delete `bootstrap-less.less` and `application.js` which might contain customizations, is that intended ?

**Comment by sapradhan** [comment]
sorry, it was my inexperience with gradle. `gradle classes` did it.

i would still like some documentation what to put in clean and .gitignore

**Comment by kensiprell** [comment]
That ```clean``` block is only used to clean the application when I"m testing the plugin. You'd definitely not want that in your own application. Thanks again for your feedback and PR.

**Comment by kensiprell** [comment]
I added a [warning](https://github.com/kensiprell/bootstrap-framework-sample/blob/master/build.gradle#L141-L142) to the sample app's ```build.gradle```.

**Comment by dezudas** [comment]
what about moving it to sass instead of less, even bootstrap 4 follows sass now. https://github.com/twbs/bootstrap-sass
