### ISSUE TITLE
Migrating it to SASS

### ISSUE THREAD

**Issue by dezudas** [kensiprell/bootstrap-framework#5]
What about migrating to SASS, as things are changing with bootstrap.
even bootstrap 4 follows SASS.
https://github.com/twbs/bootstrap-sass

**Comment by kensiprell** [comment]
I'll take a look, but I'm not familiar with SASS. What framework are you using? I don't see anything current that compiles SASS files on a JVM.

**Comment by dezudas** [comment]
We have this for asset pipeline
https://bintray.com/bertramlabs/asset-pipeline/sass-asset-pipeline/view 

and for bootstrap sass 
https://github.com/twbs/bootstrap-sass

**Comment by kensiprell** [comment]
I apologize for the late reply. I completely forgot about this issue. Unfortunately, I'm running out of time to add new features. I'm only planning on fixing bugs.
