### ISSUE TITLE
rendering pagination tag correct

### ISSUE THREAD

**Issue by tompson** [kensiprell/bootstrap-framework#6]
I used https://grails.org/plugin/twitter-bootstrap for my Grails 2.x applications and it comes with a custom pagination tag that renders the pagination bootstrap compatible - any plans on how to support bootstrap styled pagination with this plugin?

**Comment by kensiprell** [comment]
I couldn't get the twitter-bootstrap pagination tag to work for me, so I wrote my own custom one. I'm not planning on updating any of my plugins because of the time investment required, so you'll be on your own but it should be a relatively simple process.
