### ISSUE TITLE
Strange issue trying to unzip fontawesome/bootstrap zip

### ISSUE THREAD

**Issue by zypherman** [kensiprell/bootstrap-framework#7]
Hello, I have run into a weird problem where I get an error as follows:
Could not expand ZIP '/Users/username/project-directory/build/tmp/fontAwesome-v4.3.0.zip'.

When I try and run the gradle task build it throws this error saying it cannot unzip the fontAwesome zip. On further exploration is says that the referenced file isnt a zip file at all. 

I have a pretty simple grails 3 app where I have set up the plug in just like your example project. I wonder if where its pulling in the zip file from has changed it or something? 

Any help would be appreciated!

Thanks!

**Comment by kensiprell** [comment]
It looks like you're using OSX, so let me know if that's not correct. The plugin should be using this [URL](https://github.com/FortAwesome/Font-Awesome/archive/v4.3.0.zip), which works. I downloaded and unzipped the file.

Here are a couple of things to check:

- The path ```/Users/username/project-directory/build/tmp/fontAwesome-v4.3.0.zip``` doesn't look right to me. I would expect something like ```/Users/zypherman/project-directory/mySimpleGrails3App/build/tmp/fontAwesome-v4.3.0.zip```. 

- Does the plugin download and extract the Bootstrap zip without problems?

- Does the file ```/path/to/grails-app/build/tmp/fontAwesome-v4.3.0.zip``` exist? It should or else you'd get a file not found error.

- If the file above exists, can you unzip it with a utility on your computer?

- If all else fails, create a GitHub repo with your app, and I'll take a look.

Ken
