### ISSUE TITLE
Add support for SASS enabled version of bootstrap

### ISSUE THREAD

**Issue by ejaz-ahmed** [kensiprell/bootstrap-framework#8]
Even though bootstrap is written in LESS, there is official port of SASS enabled bootstrap which can be plugged in SASS powered applications. Can you add support for SASS or add some instructions to enable this if you have time for this?

**Comment by kensiprell** [comment]
I'm sorry, but I've run out of time trying to improve my plugins. I'll try and fix bugs if I can, but I don't have time to add features. Of course, you're welcome to fork it and take over.
