### ISSUE TITLE
Taglib to support bootstrap pagination

### ISSUE THREAD

**Issue by biancarosa** [kensiprell/bootstrap-framework#9]
Hi!

The original `<g:paginate/>` generates a series of links and the bootstrap styling requires a `<ul>`.

We need a taglib that overrides the default `<g:paginate/>` . The twitter-boostrap plugin managed to do it like [this](
https://github.com/groovydev/twitter-bootstrap-grails-plugin/blob/f4fe6132e045b40b5f35babb9fdd8e619428528b/grails-app/taglib/org/groovydev/TwitterBootstrapTagLib.groovy).

But maybe it's better if we look at how Grails 3 are doing the paginate method and take it as a start point.

**Comment by biancarosa** [comment]
Just for the record, I might take a look at it tomorrow and see if I can make a PR.

**Comment by kensiprell** [comment]
I no longer have the time to add new features to my plugins, so I've been limiting myself to bug fixes. However, if you you submit a PR, I'll merge it. Please include a comprehensive test. The paginate taglib was an item I had on my to-do list but never got around to implementing.

I'm planning on using the [bower-installer-gradle plugin](https://github.com/craigburke/bower-installer-gradle) in my future projects, so you might want to give that a look. Of course, it only manages the assets and doesn't come with paginate tag either.

Thanks,
Ken

**Comment by kensiprell** [comment]
This is probably better than my last recommendation:
https://github.com/craigburke/client-dependencies-gradle

I haven't done much programming lately, and I'm out of touch.
